---
title: ''
output: pdf_document
---

\section*{Remerciements}

Il y a tellement de personnes qui méritent leur place dans mes remerciements que j'espère n'oublier personne. Pour commencer, j'ai eu la chance dans mon parcours d'être entourée d'académiques aussi compétents que bienveillants. Merci à mon promoteur, Christophe Leys, de m'avoir toujours challengée. Nos divergences ce sont souvent avérées être une force. Là où ma tendance naturelle m'a fréquemment amenée à proposer des brouillons d'articles truffés de détails noyant le discours, mon promoteur m'a fréquemment rappelé l'importance d'aller à l'essentiel et d'épurer mon discours pour rester aussi didactique que possible. Cela a certainement contribué au succès des articles présentés au sein de cette thèse. Dans un registre plus privé, merci pour avoir toujours su me rassurer dans mes (fréquents) moments de doute et d'avoir toujours été là pour moi, qu'il vente ou qu'il pleuve.   

Merci aux membres de mon comité d'accompagnement pour leurs conseils avisés : à Alain Content pour son aide en ce qui concerne la programmation de données (mes scripts sont bien plus optimaux qu'ils ne l'étaient avant son intervention) et à Olivier Klein, qui a toujours pris le temps de m'aiguiller lorque j'étais en difficulté et qui restera pour toujours l'un des chercheurs que j'admire le plus, tant humainement qu'intellectuellement. 
  
Merci également aux autres membres du corps académique que j'ai eu le privilège de cotoyer. Merci à Daniël Lakens dont la rencontre a littéralement bouleversé ma carrière. Sa passion et son énergie m'ont continuellement poussée à me dépasser et je ne trouverai jamais les mots pour exprimer à quel point je lui suis reconnaissante pour tout ce qu'il m'a apporté. Merci à Christophe Ley dont la rigueur statistique s'est avérée très précieuse, notamment au cours de notre étude sur les tailles d'effet. Merci à Nicolas Kervyn, un allié et un ami qui m'a toujours soutenu et ce depuis le jour de notre rencontre, ainsi qu'à Vincent Yzerbit d'avoir accepté de faire partie de mon jury de thèse.  Enfin, merci à tous les membres académiques de l'ULB. Vous êtes nombreux à avoir enrichi mon parcours de par votre présence, et même si je n'ose citer de noms, de peur d'en oublier certains, je vous suis très reconnaissante pour tout.

L'ULB a été un lieu riche de rencontres exceptionnelles, et je souhaiterais mettre quelques petites perles en lumière. Pour commencer, je tiens à accorder une place d'honneur à Aude Fenaux. Bien plus que la secrétaire du service d'analyse des données, Aude a le don d'enchaîner au besoin les casquettes d'amie, de conseillère, de psychologue... Aude est un véritable rayon de soleil et je suis persuadée que tous les étudiants et membres du corps académique qui l'entourent mesurent la chance de travailler avec une personne aussi formidable.   

Je tiens également à mentionner certains collègues que j'affectionne particulièrement. Je pense à Kenzo, Youri, Lola, Julia, Jan, mais également à mes collègues du service d'analyse de données tels que Bruno et Tania, ainsi que tous ceux qui ont quitté l'équipe mais qui restent chers à mon coeur : Dyna, Doris, Anouk et Damien, pour ne citer que les meilleurs. 

Je souhaite également remercier les étudiants de manière générale. Ma première passion et motivation à mener cette thèse à terme a toujours été l'enseignement.  Nombreux sont les étudiants m'ayant montré des marques d'affection et de soutien au cours de ces années, et cela a été mon moteur. 

Enfin, merci à ma famille d'avoir toujours été derrière moi. La pression peut par moment me rendre "légèrement" insupportable et ils se sont toujours montrés compréhensifs malgré tout. Un merci particulier à mon père, Guy, à mes frères, Laurent et Jean-Pierre ainsi qu'à Marc d'avoir relu toutes les parties francophones de cette thèse. Par dessus tout, merci à Vincent, mon futur mari et père de mes 2 petites filles en construction, pour avoir toujours cru en moi, même lorsque je n'y arrivais plus moi-même. 
